[package]
name = "advent_of_code_2017"
version = "0.1.0"
edition = "2021"

[dependencies]
framework = { path = "./framework", package = "advent_of_code_framework" }
itertools = "0.10"

[workspace]
members = [
    "framework"
]
